config/routes.rb
Rails.application.routes.draw do
    root "articles#index"


    resources :articles do
        resources :comments
    end

    get "/login", to: "sessions#login"
    post "/login", to: "sessions#create"
    get "/logout", to: "sessions#destroy"
    post "/logout", to: "sessions#destroy"

    resources :users
    

    # get "/user/new", to: "user#new"


    # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
    include Visible

    has_many :comments, dependent: :destroy

    validates :title, presence: true
    validates :body, presence: true, length: { minimum: 10 }

end

app/models/comment.rb
class Comment < ApplicationRecord
    include Visible

    belongs_to :article

end

app/models/concerns/visible.rb
module Visible
    extend ActiveSupport::Concern

    VALID_STATUSES = ['public', 'private', 'archived']

    included do
        validates :status, inclusion: { in: VALID_STATUSES }
    end

    class_methods do 
        def status_count(article_status)
            where(status: article_status).count
        end
    end

    def show_article(article_status)
        status == article_status
    end

end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
    

    def index
      @articles = Article.all
    end


    def show
        @article = Article.find(params[:id])
    end

    def new
        if helpers.logged_in?
            @article = Article.new
        else
            redirect_to login_path
        end
    end


    def create
        
        @article = Article.create(article_params)
        @article.creator = helpers.current_user.id
        if @article.save
            redirect_to @article
        else
            render :new, status: :unprocessable_entity
        end
    end

    def edit
        if helpers.logged_in?
            @article = Article.find(params[:id])
        else
            redirect_to login_path
        end
    end
    
    def update
        @article = Article.find(params[:id])
    
        if @article.update(article_params)
            redirect_to @article
        else
            render :edit, status: :unprocessable_entity
        end
    end
    
    def destroy
        if helpers.logged_in?
            
            @article = Article.find(params[:id])
            @article.destroy
        
            redirect_to root_path, status: :see_other
        else
            redirect_to login_path
        end
    end



    private
        def article_params
            params.require(:article).permit(:title, :body, :status, :creator)
        end

  end
  

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    

    
    def create
        @article = Article.find(params[:article_id])
        # @commenter = helpers.current_user
        @comment = @article.comments.create(comment_params)
        redirect_to article_path(@article)
    end


    def destroy
        if helpers.logged_in?
            @article = Article.find(params[:article_id])
            @comment = @article.comments.find(params[:id])
            @comment.destroy
            redirect_to article_path(@article), status: 303
        else
            redirect_to login_path
        end
    end

    private
    def comment_params
        params.require(:comment).permit(:commenter, :body)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

    def create
        @user = User.find_by(username: params[:username])
        #Authanticate user credantials

        if !!@user && @user.authenticate(params[:password])
            session[:user_id] = @user.id
            redirect_to user_path(@user)
        else
            message = "Username or password is wrong"
            redirect_to login_path, notice: message
        end

    end

    def destroy
        session[:user_id] = nil
        redirect_to root_path
    end

end

app/controllers/userhome_controller.rb
class UserhomeController < ApplicationController

    def index
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController


    def show
        @user = User.find(params[:id])
    end

    def new
        @user = User.new
    end

    def create
        @user = User.create(user_params)
        if @user.save
            session[:user_id] = @user.id
            redirect_to @user
        else 
            render :new, status: :unprocessable_entity
    
        end
    end



  private
  def user_params
    params.require(:user).permit(:username, :password)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
    def logged_in?
        !!session[:user_id]
    end
    
    def current_user
        @current_user ||= User.find_by_id(session[:user_id]) if !!session[:user_id]

    end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/haml_practice_helper.rb
module HamlPracticeHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/userhome_helper.rb
module UserhomeHelper
end

app/views/articles/_form.html.erb
<%= form_with model: article do |form| %>
  <div>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
    <% article.errors.full_messages_for(:title).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :body %><br>
    <%= form.text_area :body %><br>
    <% article.errors.full_messages_for(:body).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

    <div>
        <%= form.label :status %><br>
        <%= form.select :status, ['public', 'private', 'archived'], selected: 'public' %>
    </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<%= render "/layouts/navigate"%>

<h1>Edit Article</h1>

<%= render "form", article: @article %>

app/views/articles/index.html.erb
<%= render "layouts/navigate" %>


Our blog has <%= Article.status_count('public')%> archived articles and counting! 

<ul>
  <% @articles.each do |article| %>
    <%if article.show_article('public') %>
      <li>
        <%= link_to article.title, article %>
      </li>
    <% end %>
  <% end %>
</ul>

Your private articles:

<ul>
  <% @articles.each do |article| %>
    <%if article.show_article('private') && logged_in? && current_user.id == article.creator.to_i%>
      <li>
        <%= link_to article.title, article %>
      </li>
    <% end %>
  <% end %>
</ul>

<%= link_to "New Article", new_article_path %>

app/views/articles/new.html.erb
<%= render "/layouts/navigate"%>

<h1> New Article </h1>

<%= render "form", article: @article%>

app/views/articles/show.html.erb
<%= render "/layouts/navigate"%>

<h1><%= @article.title %></h1>

<p><%= @article.body %></p>

<ul>
  <li><%= link_to "Edit", edit_article_path(@article) %></li>
  <li><%= link_to "Destroy", article_path(@article), data: {confirm: "are u sure?"}, method: :delete %></li>
    
</ul>

<h2>Comments</h2>
<%= render @article.comments%>

<h2>Add a comment:</h2>
<%= render "comments/form"%>

app/views/comments/_comment.html.erb
<% unless comment.archived?%>
    <p>
        <strong>Commenter:</strong>
        <%= comment.commenter %>
    </p>

    <p>
        <strong>Comment:</strong>
        <%= comment.body %>
    </p>

    <p>
    <%= link_to "Destroy Comment", [comment.article, comment], data: {confirm: "Are u sure?"}, method: :delete %>
    </p>

<% end %>

app/views/comments/_form.html.erb
<%= form_with model: [ @article, @article.comments.build ] do |form| %>

    <%@user = current_user%>
    <%=@user.username%><br>




    <%= form.label :Comment %><br>
    <%= form.text_area :body %>

  <p>
    <%= form.submit %>
  </p>



<% end %>

app/views/layouts/_navigate.html.erb
<div id="menu-outer">
  <div class="table">
    <ul id="horizontal-list">
        <li>
            <%=link_to "New Article", new_article_path%>
        </li>

        <li>
            <%if not logged_in?%>
                <%=link_to "Login", login_path%>
            <%else%>
                <%=link_to "Logout", "/logout"%>
            <% end %>
        </li>

        <li>
            <%=link_to "Home", root_path%>
        </li>
         <%if logged_in?%>
            <li>
                <%=link_to "Your user", user_path(current_user)%>
            </li>
        <%end %>
    </ul>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/session/index.html.erb
<h1>Session#index</h1>
<p>Find me in app/views/session/index.html.erb</p>

app/views/userhome/index.html.erb
<%= render "/layouts/navigate"%>

<h1>User</h1>

<%= render "/sessions/login", user: @user%> 

<%= link_to "New user", new_user_path %>

app/views/users/_form.html.erb
<%= form_with model: user do |form| %>
  <div>
    <%= form.label :username %><br>
    <%= form.text_field :username %>

  </div>

  <div>
    <%= form.label :password %><br>
    <%= form.password_field :password %><br>

  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/users/new.html.erb
<%= render "/layouts/navigate"%>

<h1>New user</h1>

<%= render "form", user: @user %>

app/views/users/show.html.erb
<%= render "/layouts/navigate"%>

Hei <%=@user.username%>